<?php
if (!$this->getWidget()->validateProduct()) {
    echo $this->__("Please check again Product SKU.");
    die();
}
$products = $this->getProducts();
?>
<script src="<?php echo Mage::getBaseUrl('js') ?>magestore/productwidget/bxslider/jquery.bxslider.js"></script>
<link href="<?php echo Mage::getBaseUrl('js') ?>magestore/productwidget/bxslider/jquery.bxslider.css" rel="stylesheet"/>

<div id="review-content">
    <ul class="slider">
        <?php foreach ($products as $product): ?>
            <?php
            $productImage = $this->getProductImage($product);
            $productPrice = Mage::app()->getStore()->formatPrice($product->getFinalPrice());
            $buttonText = $this->getButtonText();
            ?>
            <li class="slider-item">
                <span class="widget_link"
                      style="display:none !important;"><?php echo $this->getWidget()->getWidgetLink($product) ?></span>

                <div class="title clickable">
                    <h2 class="title">
                        <?php echo $product->getName() ?>
                    </h2>
                </div>
                <div class="image clickable">
                    <center style="height:100%;">
                        <img id="product-image" src="<?php echo $productImage ?>"
                             alt="<?php echo $product->getName() ?>">
                    </center>
                </div>
                <div class="content">
                    <?php if ($this->getExtra('hide_description') === null): ?>
                        <div class="description">
                            <p class="descriptions"><?php echo $this->getDescription($product) ?></p>
                        </div>
                    <?php endif ?>
                    <div class="addto">
                        <?php if ($this->showPrice($product)): ?>
                            <div class="price">
                                <div class="new-price">
                                    <?php echo $this->formatPrice($product->getFinalPrice()) ?>
                                </div>
                                <?php if ($product->getSpecialPrice()): ?>
                                    <div>
                                        <span class="old-price"
                                              style="display: inline-block"><?php echo $this->formatPrice($product->getPrice()) ?></span>&nbsp;&nbsp;
                                    <span class="special-offer">
                                        <?php echo $this->getSpecialOffer($product) ?>
                                    </span>
                                    </div>
                                <?php endif; ?>
                            </div>
                        <?php endif; ?>
                        <?php if ($this->getExtra('use_button')): ?>
                            <a class="widget-button" target="_blank"
                               href="<?php echo $this->getWidget()->getButtonLink($product) ?>"
                               style="float:right;"><?php echo $buttonText ?></a>
                        <?php endif ?>
                    </div>
                </div>
            </li>
        <?php endforeach ?>
    </ul>
</div>
<script>
    $(document).ready(function () {
        $('.clickable').click(function (event) {
            var url = $(this).closest('.slider-item').find('.widget_link').text();
            window.open(url + '?domain=' + encodeURIComponent(domain), '_blank');
        });
        $('.widget-button').each(function (index, el) {
            var h = $(el).prop('href');
            $(el).prop('href', h + 'domain/' + encodeURIComponent(domain));
        })
        <?php if(!$this->getExtra('auto_height')): ?>
        $('#review-content .slider li').each(function (index, el) {
            var _this = $(el);
            <?php echo "_this.find('.image').height($('#review-content').outerHeight() - _this.find('.title').outerHeight() - _this.find('.content').outerHeight()-10);" ?>
        });
        <?php endif; ?>

        $('#review-content').hover(function () {
            $('.bx-controls-direction').fadeIn();
        }, function () {
            $('.bx-controls-direction').fadeOut();
        });
        $('.slider').bxSlider({
            mode: 'fade',
            infiniteLoop: true,
            speed: 1000,
            auto: true,
            controls: true,
            pager: false
        });
    });
</script>
<style type="text/css">
    #review {
        margin-left: 15%;
    }

    .clickable {
        cursor: pointer;
    }

    #review-content {
        background-color: #<?php echo $this->getExtra('background_color') ?>
    }

    #review-content h2.title {
        padding: 8px 11px;
        text-align: center;
        color: #<?php echo $this->getExtra('title_color') ?>;
        text-transform: uppercase;
        font-weight: bold;
        font-size: 12px;
        box-sizing: border-box;
        background-color: #<?php echo $this->getExtra('title_background') ?>
    }

    #review-content img#product-image {
        height: 100%;
        width: 80%;
        border: 1px solid #ececec;
    }

    #review-content .image.clickable {
        margin-bottom: 5px;
    }

    #review-content .content {
        padding: 10px 10px 0px;
    }

    #review-content .description p {
        color: #<?php echo $this->getExtra('description_color') ?>;
        text-align: center;
        font-size: 13px;
    }

    #review-content .addto {
        overflow: hidden;
    }

    #review-content .addto .price {
        float: left;
        font-size: 20px;
        color: #<?php echo $this->getExtra('price_color') ?>;
        font-weight: bold;
        margin-top: 5px;
        width: 55%;
    }

    #review-content .addto .price .old-price {
        display: inline-block;
        font-size: 70%;
        color: gray;
        text-decoration: line-through;
        float: left;
    }

    #review-content .addto .price .special-offer {
        display: inline-block;
        font-size: 70%;
        color: #<?php echo $this->getExtra('price_color') ?>;
        float: left;
        margin-left: 5px;
    }

    .widget-button {
        background-color: #<?php echo $this->getExtra('button_color') ?>;
        padding: 8px 15px;
        text-decoration: none;
        border-radius: 5px;
        color: #<?php echo $this->getExtra('button_text_color') ?>;
        text-transform: uppercase;
        width: 40%;
        box-sizing: border-box;
        text-align: center;
        font-size: 15px;
        display: inline-block;
    }

    .bx-wrapper {
        height: 100%;
        position: static;
    }

    .bx-viewport {
        height: 100% !important;
        background-color: #<?php echo $this->getExtra('background_color') ?> !important;
        border: none;
        box-shadow: none;
        left: 0;
    }

    .slider {
        width: 100%;
    }

    .slider-item {
        width: 100%;
    }

    .bx-wrapper .bx-controls-direction a {
        opacity: 0.8;
    }

    .bx-controls-direction {
        display: none
    }
</style>