<?php
if (!$this->getWidget()->validateProduct()) {
    echo $this->__("Please check again Product SKU.");
    die();
}
$products = $this->getProducts();
?>
<script src="<?php echo Mage::getBaseUrl('js') ?>magestore/productwidget/bxslider/jquery.bxslider.js"></script>
<link href="<?php echo Mage::getBaseUrl('js') ?>magestore/productwidget/bxslider/jquery.bxslider.css" rel="stylesheet"/>


<div id="review-content">
    <ul class="slider">
        <?php foreach ($products as $product): ?>
            <?php
            $productImage = $this->getProductImage($product);
            $productPrice = $this->getProductPrice($product);
            $buttonText = $this->getButtonText();
            ?>
            <li class="slider-item">
                <span class="widget_link"
                      style="display:none !important;"><?php echo $this->getWidget()->getWidgetLink($product) ?></span>

                <div class="content">
                    <div class="image clickable">
                        <center style="height:100%;">
                            <img id="product-image" src="<?php echo $productImage ?>"
                                 alt="<?php echo $product->getName() ?>">
                        </center>
                    </div>
                    <?php if ($this->showPrice($product)): ?>
                        <div class="price">
                            <p class="new-price">
                                <?php echo $this->formatPrice($product->getFinalPrice()) ?>
                            </p>
                            <?php if ($product->getSpecialPrice()): ?>
                                <p style="display: inline-block">
                                    <span
                                        class="old-price"><?php echo $this->formatPrice($product->getPrice()) ?></span>
                                    <span class="special-offer">
                                        <?php echo $this->getSpecialOffer($product) ?>
                                    </span>
                                </p>
                            <?php endif; ?>
                        </div>
                    <?php endif; ?>
                    <div class="title-wrapper">
                        <h2 class="title clickable">
                            <?php echo $product->getName() ?>
                        </h2>
                    </div>
                    <?php if ($this->getExtra('hide_description') === null): ?>
                        <div class="description">
                            <p class="descriptions"><?php echo $this->getDescription($product) ?></p>
                        </div>
                    <?php endif ?>

                    <?php if ($this->getExtra('use_button')): ?>
                        <div class="arow button-buy">
                            <a class="widget-button" target="_blank"
                               href="<?php echo $this->getWidget()->getButtonLink($product) ?>"><?php echo $buttonText ?></a>
                        </div>
                    <?php endif ?>
                </div>
            </li>
        <?php endforeach ?>
    </ul>
</div>


<script>
    $(document).ready(function () {
        $('.clickable').click(function (event) {
            var url = $(this).closest('.slider-item').find('.widget_link').text();
            window.open(url + '?domain=' + encodeURIComponent(domain), '_blank');
        });
        $('.widget-button').each(function (index, el) {
            var h = $(el).prop('href');
            $(el).prop('href', h + 'domain/' + encodeURIComponent(domain));
        });
        <?php if(!$this->getExtra('auto_height')): ?>
        $('#review-content .slider li .content').each(function (index, el) {
            var _this = $(el);
            console.log(_this.find('.price').outerHeight());
            console.log(_this.find('.title-wrapper').outerHeight());
            console.log(_this.find('.description').outerHeight());
            console.log(_this.find('.button-buy').outerHeight());
            <?php echo "_this.find('.image img').height($('#review-content').outerHeight(true)
                        - _this.find('.price').outerHeight(true)
                        - _this.find('.title-wrapper').outerHeight(true)
                        - _this.find('.description').outerHeight(true)
                        - _this.find('.button-buy').outerHeight(true) -20);" ?>
        });
        <?php endif; ?>
        $('#review-content').hover(function () {
            $('.bx-controls-direction').fadeIn();
        }, function () {
            $('.bx-controls-direction').fadeOut();
        });
        $('.slider').bxSlider({
            mode: 'fade',
            infiniteLoop: true,
            speed: 1000,
            auto: true,
            controls: true,
            pager: false,
        });
    });
</script>


<style type="text/css">
    #review-content {
        font-family: Arial, sans-serif;
    }

    #review-content .content {
        margin: 0 auto;
        width: 80%;
    }

    .arow {
        margin-top: 7px;
    }

    .clickable {
        cursor: pointer;
    }

    #review-content .slider .image img {
        width: 100%;
        height: 100%;
    }

    #review-content .price {
        text-align: left;
        font-size: 17px;
        /*font-weight: bold;*/
        color: #<?php echo $this->getExtra('price_color') ?>;
        overflow: auto;
    }

    #review-content .price .old-price {
        display: inline-block;
        font-size: 13px;
        color: gray;
        text-decoration: line-through;
    }
    #review-content .price .special-offer{
        font-size: 13px;
        color: #<?php echo $this->getExtra('price_color') ?>;
    }

    #review-content h2.title {
        text-align: left;
        background-color: #<?php echo $this->getExtra('title_background') ?>;
        font-size: 13px;
        box-sizing: border-box;
        color: #<?php echo $this->getExtra('title_color') ?>;
        font-weight: bold;
        width: 100%;
    }

    #review-content .descriptions {
        color: #<?php echo $this->getExtra('description_color') ?>;
        text-align: left;
        font-size: 13px;
    }

    #review-content .button-buy {
        clear: both;
        text-align: center;
        min-height: 30px;
    }

    #review-content .widget-button {
        background-color: #<?php echo $this->getExtra('button_color') ?>;
        padding: 7px 30px;
        border-radius: 2px;
        color: #<?php echo $this->getExtra('button_text_color') ?>;
        text-decoration: none;
        display: inline-block;
    }

    .bx-viewport {
        background-color: #<?php echo $this->getExtra('background_color') ?> !important;
    }

    .bx-wrapper .bx-controls-direction a {
        opacity: 0.8;
    }

    #review-content .bx-wrapper .bx-viewport {
        border: none;
        box-shadow: none;
        left: 0;
    }

    #review-content .bx-wrapper {
        position: static;
    }

    #review-content .bx-controls-direction {
        display: none
    }
</style>